### ISSUE TITLE
Adding RTEMS support for GDB

### ISSUE THREAD

**Issue by heshamelmatary** [adapteva/epiphany-binutils-gdb#2]
Hi, 

Can this commit [1] be applied to "epiphany-gdb-7.8" branch (and maybe the default you're working with now)? If not please tell me to create a new pull request for it. 

[1] https://github.com/adapteva/epiphany-binutils-gdb/commit/b6c483b4a98424731e6e44558cb4b9863751fb1b

Thanks,
Hesham

**Comment by olajep** [comment]
Fixed in e1c7583cca5be84a6775d142213b332989cf9a16

**Comment by heshamelmatary** [comment]
Hi,

Thanks for merging the pull request(s). I am submitting patches to RTEMS Source Builder (RSB) to build the tools from these branches:
- epiphany-binutils-2.23-software-cache
- epiphany-gcc-4.9
- epiphany-gdb-7.8

If these are not the correct (stable) ones kindly let me know. Also, are you going to push your work upstream? Basically RTEMS fetch from there and fetching from external repos (like Adapteva) is not very desirable.

**Comment by olajep** [comment]
Hi,

On 2015-04-22 14:11, Hesham ALMatary wrote:

> Hi,
> 
> Thanks for merging the pull request(s). I am submitting patches to RTEMS Source Builder (RSB) to build the tools from these branches:
> - epiphany-binutils-2.23-software-cache
> - epiphany-gcc-4.9
> - epiphany-gdb-7.8
> 
> If these are not the correct (stable) ones kindly let me know.
> 
> epiphany-binutils-2.23-software-cache
> epiphany-gcc-4.8-software-cache
> epiphany-gdb-7.6

That configuration is used in both the eSDK 2014.11 and 2015.1 releases. Having said that we have had epiphany-gcc-4.9 on the master branch for a while and I have not seen any problems with it so far. (And we should bump to at least gdb 7.8 and binutils 2.24 when the build issue I mentioned earlier is sorted out)

> Also, are you going to push your work upstream? Basically RTEMS fetch from there and fetching from external repos (like Adapteva) is not very desirable.
> 
> That is the idea but as much as we would like to it's not going to happen anytime soon. First we need to catch up with upstream for all toolchain components which will require some work. Other things have higher priority right now.

// Ola

**Comment by heshamelmatary** [comment]
Thanks for the details. We will be working from the repos I mentioned above (tested and working fine with RTEMS), I just hope that my gotten-merged pull requests will be populated for any other newly-created branches for all the tools. 

Thanks,
Hesham

P.S This is the last pending pull request for building epiphany-rtems4.11-gdb. https://github.com/heshamelmatary/epiphany-binutils-gdb/commit/acb849086e6e58a10ed166c948628ce3b7d8fcca
